=== AnaArias12/LMA_2/biblioteca.dtd
<!--definicion de elementos y atributos libros-->

<!ELEMENT biblioteca (libros, revistas, periodicos)>
<!ELEMENT libros (libro+)>
<!ATTLIST libros id CDATA #REQUIRED>
<!ELEMENT libro (titulo, capitulo, indice, sipnosis)>
<!ATTLIST libro tipo_clase CDATA #REQUIRED>
<!ATTLIST libro numero_paginas_libro CDATA #REQUIRED>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT capitulo (titulo_capitulo, contenido)>
<!ATTLIST capitulo numero_paginas_capitulo CDATA #REQUIRED>
<!ELEMENT titulo_capitulo (#PCDATA)>
<!ELEMENT contenido (#PCDATA)>
<!ATTLIST contenido xmlns:xlink CDATA #REQUIRED>
<!ELEMENT indice (#PCDATA)>
<!ELEMENT sipnosis (#PCDATA)>

<!--definicion de elementos y atributos revistas-->

<!ELEMENT revistas (revista+)>
<!ATTLIST revistas id CDATA #REQUIRED>
<!ELEMENT revista (titulo, numero_revista, indice, seccionr)>
<!ATTLIST revista tipo_clase CDATA #REQUIRED>
<!ATTLIST revista numero_paginas CDATA #REQUIRED>
<!--<!ELEMENT titulo (#PCDATA)>-->
<!ELEMENT numero_revista (#PCDATA)>
<!--<!ELEMENT indice (#PCDATA)>-->
<!ELEMENT seccionr (contenido)>
<!ATTLIST seccionr numero_paginas CDATA #REQUIRED>
<!--<!ELEMENT contenido (#PCDATA)>-->
<!ATTLIST contenido xmlns:xlink CDATA #REQUIRED>

<!--definicion de elementos y atributos periodicos-->  

<!ELEMENT periodicos (periodico+)>
<!ATTLIST periodicos id CDATA #REQUIRED>
<!ELEMENT periodico (seccion, indice)>
<!ATTLIST periodico tipo_clase CDATA  #REQUIRED>
<!ATTLIST periodico fecha_publicacion CDATA #REQUIRED>
<!--<!ELEMENT seccion (#PCDATA)>-->
<!ELEMENT seccion (articulos, contenido)>
<!ATTLIST seccion tipo_seccion CDATA #REQUIRED>
<!ELEMENT articulos (#PCDATA)>
<!ATTLIST articulos autor CDATA #REQUIRED>
<!--<!ELEMENT contenido (#PCDATA)>-->
<!ATTLIST contenido xmlns:xlink CDATA #REQUIRED>

=== AnaArias12/LMA_2/biblioteca_dtd.xml
<?xml version="1.0" encoding="UTF-8"?>


<!DOCTYPE biblioteca SYSTEM "biblioteca.dtd">


<biblioteca>

    <libros id = "L0001">
        <libro tipo_clase = "novela" numero_paginas_libro = "500">
            <titulo>TituloNovela</titulo>
            <capitulo numero_paginas_capitulo= "100">
                <titulo_capitulo>Novela1</titulo_capitulo>
                <contenido  xmlns:xlink ="https://institutotecnologico.edix.com/es/web/mp_0373-lenguajes-de-marcas-y-sistemas-de-gestion-2021-daw-3t-ord-de-informacion-2021-damdaw-3t-"/>
            </capitulo>
            <indice>1</indice>
            <sipnosis>Lorem Ipsum es simplemente el texto de
                     relleno de las imprentas y archivos de texto
            </sipnosis>
         </libro>

        <libro tipo_clase = "infantil" numero_paginas_libro = "500">
            <titulo>TituloInfantil</titulo>
            <capitulo numero_paginas_capitulo = "100">
                <titulo_capitulo>Infatil1</titulo_capitulo>
                <contenido  xmlns:xlink ="URL_infantil"/>
            </capitulo>
            <indice>2</indice>
            <sipnosis>Lorem Ipsum es simplemente el texto
                     de relleno de las imprentas y archivos de texto
            </sipnosis>
        </libro>

        <libro tipo_clase = "didactico" numero_paginas_libro = "500">
            <titulo>TituloDidactico</titulo>
            <capitulo numero_paginas_capitulo = "100">
                <titulo_capitulo>Didactico1</titulo_capitulo>
                <contenido  xmlns:xlink ="URL_didactico"/>
            </capitulo>
            <indice>3</indice>
            <sipnosis>Lorem Ipsum es simplemente el texto
                     de relleno de las imprentas y archivos de texto
            </sipnosis> 
        </libro>
    </libros>


    <revistas id = "R0002">
        <revista tipo_clase = "informatica" numero_paginas = "200">
            <titulo>tituloinformatica</titulo>
            <numero_revista>01</numero_revista>
            <indice>1</indice>
            <seccionr numero_paginas = "200">
                <contenido  xmlns:xlink ="URL_informatica"/>
            </seccionr>
        </revista>

        <revista tipo_clase = "corazon" numero_paginas = "200">
            <titulo>titulocorazon</titulo>
            <numero_revista>02</numero_revista>
            <indice>2</indice>
            <seccionr numero_paginas = "200">
                <contenido  xmlns:xlink ="URL_corazon"/>
            </seccionr>
        </revista> 

        <revista tipo_clase = "coches" numero_paginas = "200">
         <titulo>titulocoches</titulo>
            <numero_revista>03</numero_revista>
            <indice>3</indice>
            <seccionr numero_paginas = "200">
                <contenido  xmlns:xlink ="URL_biblioteca"/>
            </seccionr>
        </revista>

        <revista tipo_clase = "investigacion" numero_paginas = "200">
         <titulo>tituloinvestigacion</titulo>
            <numero_revista>04</numero_revista>
            <indice>4</indice>
            <seccionr numero_paginas = "200">
                <contenido  xmlns:xlink ="URL_biblioteca"/>
            </seccionr>
        </revista>

        <revista tipo_clase = "otras" numero_paginas = "200">
        <titulo>titulootras</titulo>
            <numero_revista>05</numero_revista>
            <indice>5</indice>
            <seccionr numero_paginas = "200">
                <contenido  xmlns:xlink ="URL_biblioteca"/>
            </seccionr>
        </revista>

    </revistas>


    <periodicos id = "P0003">
        <periodico tipo_clase = "nacionales" fecha_publicacion = "2021-05-11">
            <seccion tipo_seccion = "economica">
                <articulos autor = "xxx"></articulos>
                <contenido  xmlns:xlink ="URL_biblioteca"/>          
            </seccion>
            <indice>1</indice>
        </periodico>
        <periodico tipo_clase = "opinion" fecha_publicacion = "2021-05-11">
            <seccion tipo_seccion = "economica">
                <articulos autor = "xxx"></articulos>
                <contenido  xmlns:xlink ="URL_biblioteca"/>           
            </seccion>
            <indice>1</indice>
        </periodico>
        <periodico tipo_clase = "deporte" fecha_publicacion = "2021-05-11">
            <seccion tipo_seccion = "economica">
                <articulos autor = "xxx"></articulos>
                <contenido  xmlns:xlink ="URL_biblioteca"/>           
            </seccion>
            <indice>1</indice>
        </periodico>
        <periodico tipo_clase = "internacionales" fecha_publicacion = "2021-05-11">
            <seccion tipo_seccion = "economica">
                <articulos autor = "xxx"></articulos>
                <contenido  xmlns:xlink ="URL_biblioteca"/>          
            </seccion>
            <indice>1</indice>
        </periodico>

        <periodico tipo_clase = "internacionales" fecha_publicacion = "2021-05-11">
            <seccion tipo_seccion = "economica">
                <articulos autor = "xxx"></articulos>
                <contenido  xmlns:xlink ="URL_biblioteca"/>          
            </seccion>
            <indice>1</indice>
        </periodico>
        <periodico tipo_clase = "opinion" fecha_publicacion = "2021-05-11">
            <seccion tipo_seccion = "economica">
                <articulos autor = "xxx"></articulos>
                <contenido  xmlns:xlink ="URL_biblioteca"/>          
            </seccion>
            <indice>1</indice>
        </periodico>
        <periodico tipo_clase = "deporte" fecha_publicacion = "2021-05-11">
            <seccion tipo_seccion = "economica">
                <articulos autor = "xxx"></articulos>
                <contenido  xmlns:xlink ="URL_biblioteca"/>           
            </seccion>
            <indice>1</indice>
        </periodico>
        <periodico tipo_clase = "internacionales" fecha_publicacion = "2021-05-11">
            <seccion tipo_seccion = "economica">
                <articulos autor = "xxx"></articulos>
                <contenido  xmlns:xlink ="URL_biblioteca"/>          
            </seccion>
            <indice>1</indice>
        </periodico>
    </periodicos>
</biblioteca>
